### ISSUE TITLE
The Super Star theme can be overlaped

### ISSUE THREAD

**Issue by Hugman76** [Hugman76/Mubble#7]
**Describe the bug**
When the super star is eaten, a theme is played for 30 seconds. If you eat two super stars in a row, the theme is overlaped and plays twice in the same time.

**To Reproduce**
1. Eat 2 Super Star in survival mode.
2. Ear carefully.

**Expected behavior**
The super star theme should be stopped when a super star is eaten and then play just after it.

**Comment by Hugman76** [comment]
A line for stopping the sound should be added right before [this line](https://github.com/Hugman76/Mubble/blob/027ef6ee1aa7f912420fe73cebfc690b458b1878/java/hugman/mod/objects/items/ItemSuperStar.java#L29) or [this one](https://github.com/Hugman76/Mubble/blob/027ef6ee1aa7f912420fe73cebfc690b458b1878/java/hugman/mod/objects/items/ItemSuperStar.java#L34). I need to search for the method of stopping a sound, which I don't know right now.

**Comment by FVbico** [comment]
Maybe you can find it by looking into the stopsound command?

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.4**.

**Comment by Sven792** [comment]
This bug still occurs in the latest development version, I mean.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.4**.
(It's fixed in a version that is not released yet! 😋)

**Comment by Sven792** [comment]
The bug is still there in v2.0.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug will be fixed for v**2.0.1**.
